# Generated by Django 4.2.15 on 2024-09-23 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.TextField(blank=True, null=True)),
                ("orkid_id", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=10)),
                ("public_key", models.TextField(blank=True, null=True)),
                ("encrypted_private_key", models.BinaryField(blank=True, null=True)),
                (
                    "registration_status",
                    models.CharField(default="Pending", max_length=20),
                ),
                ("is_approved", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("orkid_id", "email", "role")},
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=256, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
